name: "Setup pscale (unofficial)"
description: "Installs the PlanetScale CLI (pscale) for use in GitHub Actions."
author: "willgeorgetaylor"
branding:
  icon: "database"
  color: "blue"
inputs:
  github-token:
    description: "GitHub token to use for downloading the pscale binary."
    required: true
  version:
    description: "Version of pscale to install. i.e. v0.106.0. Defaults to latest version."
    required: false
    default: "latest"
runs:
  using: "node20"
  main: "dist/index.js"
